### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by nima** [dcreager/graffle-export#1]
Hi there!

I have a small problem on first use...

% graffle.sh pdf 0x002-unwinding.graffle 0x002-unwinding.pdf
OmniGraffle Professional 5
/Users/nima/bin/graffle.scpt: execution error: OmniGraffle Professional 5 got an error: The document cannot be exported to the "pdf" format. (-50)
%

% graffle.sh 0x002-unwinding.graffle 0x002-unwinding.pdf
OmniGraffle Professional 5
/Users/nima/bin/graffle.scpt: execution error: OmniGraffle Professional 5 got an error: The document cannot be exported to the "pdf" format. (-50)
%

This is probably due to the fact that you wrote this for version 4, and I'm on 5 - did you have any plans of updating it?

**Comment by dcreager** [comment]
Yeah, I wouldn't be surprised if it barfs on version 5.  I'm probably going to bite the bullet and upgrade to version 5 sometime in the next couple of weeks, at which point I can look at fixing the script to work with it.  If you have any experience hacking on AppleScript, and have more time than me, I'd be happy to take any patches.

**Comment by dcreager** [comment]
Have OmniGraffle guess if no format given on command line

Before, if you didn't pass an export format into the graffle.sh
script, it would use “pdf” as a default.  Unfortunately, it seems like
several of the format names that worked with OmniGraffle 4 no longer
work with OmniGraffle 5 — and “pdf” is one of those.  “PDF” and “PDF
vector image” (the string that appears in the Export dialog) don't
work either.

Luckily, we can leave off the “as format” portion of the “save”
AppleScript command; in this case, it seems like OmniGraffle guesses
the output format based on the extension of the output filename.  This
gives us a workaround: instead of guessing what variation of “PDF” to
use as the format name, just make sure to pass in an output filename
that ends in “.pdf”.

Closed by b605b461a29b73ab4c21bd42b48549bd8bad8fcc

**Comment by dcreager** [comment]
I marked this as closed with the most recent commit — it should hopefully work now with OmniGraffle 5 if you leave out the format parameter when you run graffle.sh.  If that doesn't work, we'll reopen the ticket and keep digging.
